name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:


concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    if: github.repository_owner == 'vladiliescu'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Set up uv
      uses: astral-sh/setup-uv@v6

    - name: Install build dependencies (uv)
      run: uv sync --group build

    - name: Build package
      run: uv run python -m build

    - name: Check package
      run: uv run python -m twine check dist/*

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: uv run python -m twine upload dist/*
